// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtKmpnoIZJHFGeZENFHwMAJqitZFotVDg',
    appId: '1:1078229229574:web:682a248d96940952216387',
    messagingSenderId: '1078229229574',
    projectId: 'bankapp-f03ff',
    authDomain: 'bankapp-f03ff.firebaseapp.com',
    databaseURL: 'https://bankapp-f03ff-default-rtdb.firebaseio.com',
    storageBucket: 'bankapp-f03ff.appspot.com',
    measurementId: 'G-G4RGSYSQT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8sZtk7o1tQUDwkoyRpU8p4XNdUwSY0NE',
    appId: '1:1078229229574:android:dad9db2c6d5ff6af216387',
    messagingSenderId: '1078229229574',
    projectId: 'bankapp-f03ff',
    databaseURL: 'https://bankapp-f03ff-default-rtdb.firebaseio.com',
    storageBucket: 'bankapp-f03ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBTv-6ax88xXDAbQ8Ro8GQvff2QTsc168',
    appId: '1:1078229229574:ios:ab2b0ab6d24ce111216387',
    messagingSenderId: '1078229229574',
    projectId: 'bankapp-f03ff',
    databaseURL: 'https://bankapp-f03ff-default-rtdb.firebaseio.com',
    storageBucket: 'bankapp-f03ff.appspot.com',
    iosBundleId: 'com.example.bancointerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBTv-6ax88xXDAbQ8Ro8GQvff2QTsc168',
    appId: '1:1078229229574:ios:ab2b0ab6d24ce111216387',
    messagingSenderId: '1078229229574',
    projectId: 'bankapp-f03ff',
    databaseURL: 'https://bankapp-f03ff-default-rtdb.firebaseio.com',
    storageBucket: 'bankapp-f03ff.appspot.com',
    iosBundleId: 'com.example.bancointerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtKmpnoIZJHFGeZENFHwMAJqitZFotVDg',
    appId: '1:1078229229574:web:e626483bc9859e87216387',
    messagingSenderId: '1078229229574',
    projectId: 'bankapp-f03ff',
    authDomain: 'bankapp-f03ff.firebaseapp.com',
    databaseURL: 'https://bankapp-f03ff-default-rtdb.firebaseio.com',
    storageBucket: 'bankapp-f03ff.appspot.com',
    measurementId: 'G-FPX8WFMMMB',
  );
}
